config/routes.rb
HaimsRails::Application.routes.draw do
  # devise
  devise_for :users

  # root
  root :to => 'home#index'

  # リモートコントロール
  resources :remote, :defaults => { :format => 'html' }, :only => [:index] do
    member do
      post :ir_send
    end
  end

  # 管理ページ
  resources :management, :defaults => { :format => 'html' }, :only => [:index]
  namespace :management do
    # マイコンボード
    resources :board, :defaults => { :format => 'html' }
    # 制御対象機器一覧
    resources :device, :defaults => { :format => 'html' }, :except => [:edit, :update] do
      # 赤外線リモコンの信号
      resources :ir_signal, :defaults => { :format => 'html' }, :except => [:index, :show, :edit, :update]
    end
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :name, :serial_port

  validates :name, :presence => true
  validates :serial_port, :presence => true
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :ir_signal

  validates :name, :presence => true
end

app/models/ir_signal.rb
class IrSignal < ActiveRecord::Base
  attr_accessible :data, :device_id, :name

  belongs_to :device

  validates :name, :presence => true
  validates :data, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    board = Board.where("name = ?", "main")
    sp = SerialPort.new(board.first.serial_port, 9600, 8, 1, SerialPort::NONE)
    sleep 1
    sp.puts "2\n"
    while sp.gets do
      @lx = sp.gets
      break
    end

    sp.puts "3\n"
    while sp.gets do
      @temp = sp.gets
      break
    end

    sp.close
  end
end

app/controllers/management/board_controller.rb
# encoding: utf-8

class Management::BoardController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(params[:board])

    if @board.save
      redirect_to management_board_index_path, :notice => "登録しました"
    else
      redirect_to edit_management_board_path, :alert => "登録に失敗しました"
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.assign_attributes(params[:board])
    if @board.save
      redirect_to management_board_index_path, :notice => "更新しました"
    else
      redirect_to edit_management_board_path, :alert => "更新に失敗しました"
    end
  end

  def destroy
    Board.find(params[:id]).destroy
    redirect_to management_board_index_path, :notice => "削除しました"
  end
end

app/controllers/management/device_controller.rb
# encoding: utf-8

class Management::DeviceController < ApplicationController
  def index
    @devices = Device.all
  end

  def show
    @device = Device.includes(:ir_signal).find(params[:id])
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(params[:device])

    if @device.save
      redirect_to management_device_index_path, :notice => "登録しました"
    else
      redirect_to edit_management_device_index_path, :notice => "登録に失敗しました"
    end
  end

  def destroy
    Device.find(params[:id]).destroy
    redirect_to management_device_index_path(:id => params[:device_id]), :notice => "削除しました"
  end
end

app/controllers/management/ir_signal_controller.rb
# encoding: utf-8

class Management::IrSignalController < ApplicationController
  def new
    @ir_signal = IrSignal.new
  end

  def create
    @ir_signal = IrSignal.new(params[:ir_signal])

    if @ir_signal.save
      redirect_to management_device_path(:id => params[:device_id]), :notice => "登録しました"
    else
      redirect_to new_management_device_ir_signal_path, :alert => "登録に失敗しました"
    end
  end

  def destroy
    IrSignal.find(params[:id]).destroy
    redirect_to management_device_path(:id => params[:device_id]), :notice => "削除しました"
  end
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  def index
  end
end

app/controllers/remote_controller.rb
# encoding: utf-8

class RemoteController < ApplicationController
  def index
    @devices = Device.all
  end

  def ir_send
    board = Board.where("name = ?", "main")
    signal = IrSignal.find(params[:id])

    sp = SerialPort.new(board.first.serial_port, 9600, 8, 1, SerialPort::NONE)
    sleep 1
    sp.puts "0\n"
    sleep 0.8
    sp.puts signal.data + "\n"
    sleep 0.8
    sp.close

    redirect_to remote_index_path, :notice => "送信しました"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/management/board_helper.rb
module Management::BoardHelper
end

app/helpers/management/device_helper.rb
module Management::DeviceHelper
end

app/helpers/management/ir_signal_helper.rb
module Management::IrSignalHelper
end

app/helpers/management_helper.rb
module ManagementHelper
end

app/helpers/remote_helper.rb
module RemoteHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
  <p>現在の</p>
  <table class="table">
    <tr>
      <th>気温</th>
      <th>照度</th>
    </tr>
    <tr>
      <td><%= @temp %> ℃</td>
      <td><%= @lx %> lx</td>
    </tr>
  </table>
  <div align="right">
    <small><%= DateTime.now.in_time_zone('Tokyo') %> 取得</small>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HaimsRails" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Haims", root_path, :class => "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to "リモートコントロール", remote_index_path %></li>
                <li><%= link_to "管理ページ", management_index_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete  %></li>
              <% else %>
                <li><%= link_to "ログイン", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
         <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <br />

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/management/board/edit.html.erb
<legend>編集</legend>

<%= form_for [:management, @board], :html => {:class => "form-horizontal"} do |f| %>
  <div class="control-group">
    <label class="control-label">名前</label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">シリアルポート</label>
    <div class="controls">
      <%= f.text_field :serial_port %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "更新", :class => "btn btn-primary" %>
    <%= link_to "キャンセル", management_board_index_path, :class => "btn" %>
    <%= link_to "削除", management_board_path, :method => :delete, :confirm => "本当に削除しますか？", :class => "btn btn-danger", :style => "float: right;" %>
  </div>
<% end %>

app/views/management/board/index.html.erb
<legend>マイコンボード一覧</legend>

<%= link_to "新規登録", new_management_board_path, :class => "btn" %>
<table class="table">
  <tr>
    <th>名前</th>
    <th>シリアルポート</th>
  </tr>
  <% @boards.each do |i| %>
    <tr>
      <td><%= link_to i.name, edit_management_board_path(:id => i.id) %></td>
      <td><%= i.serial_port %></td>
    </tr>
  <% end %>
</table>

app/views/management/board/new.html.erb
<legend>新規登録</legend>

<%= form_for @board, :url => management_board_index_path, :class => "form-horizontal" do |f| %>
  <div class="control-group">
    <label class="control-label">名前</label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">シリアルポート</label>
    <div class="controls">
      <%= f.text_field :serial_port %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "登録", :class => "btn btn-primary" %>
    <%= link_to "キャンセル", management_board_index_path, :class => "btn" %>
  </div>
<% end %>

app/views/management/device/index.html.erb
<legend>リモートコントロール対象機器一覧</legend>

<%= link_to "新規登録", new_management_device_path, :class => "btn" %>
<table class="table">
  <tr>
    <th>名前</th>
    <th>説明</th>
  </tr>
  <% @devices.each do |i| %>
    <tr>
      <td><%= link_to i.name, management_device_path(:id => i.id) %></td>
      <td><%= i.description %></td>
    </tr>
  <% end %>
</table>

app/views/management/device/new.html.erb
<legend>新規登録</legend>

<%= form_for @device, :url => management_device_index_path, :class => "form-horizontal" do |f| %>
  <div class="control-group">
    <label class="control-label">名前</label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

   <div class="control-group">
    <label class="control-label">説明</label>
    <div class="controls">
      <%= f.text_field :description %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "登録", :class => "btn btn-primary" %>
    <%= link_to "キャンセル", management_device_index_path, :class => "btn" %>
  </div>
<% end %>

app/views/management/device/show.html.erb
<legend><%= @device.name %></legend>
<p><%= @device.description %></p>

<br / >

<h4>登録済みリモコン信号</h4>
<%= link_to "新規登録", new_management_device_ir_signal_path(:device_id => @device.id), :class => "btn" %><br />
<% if @device.ir_signal.count > 0 %>
  <table class="table">
    <tr>
      <th>名前</th>
      <th>データ</th>
      <th>登録日時</th>
      <th></th>
    </tr>

    <% @device.ir_signal.each do |i| %>
      <tr>
        <td><%= i.name %></td>
        <td><%= i.data.length > 50 ? i.data[0, 50] + "..." : i.data %></td>
        <td><%= i.created_at %></td>
        <td>
          <%= link_to "削除", management_device_ir_signal_path(:device_id => @device.id, :id => i.id), :method => :delete, :confirm => "本当に削除しますか？", :class => "btn btn-danger", :style => "float: right;" %>
        </td>
      </tr>
    <% end %>
  </table>
  <% else %>
    <br /><p>リモコン信号が登録されていません。</p>
<% end %>

<div class="form-actions">
  <%= link_to "削除", management_device_path(:id => @device.id), :method => :delete, :confirm => "本当に削除しますか？", :class => "btn btn-danger" %>
</div>

app/views/management/index.html.erb
<legend>管理ページ</legend>

<ul>
  <li><%= link_to "マイコンボード一覧", management_board_index_path %></li>
  <li><%= link_to "リモートコントロール対象機器一覧", management_device_index_path %></li>
</ul>

app/views/management/ir_signal/new.html.erb
<legend>リモコン信号の新規登録</legend>

<%= form_for @ir_signal, :url => management_device_ir_signal_index_path, :html => {:class => "form-horizontal"} do |f| %>
  <%= f.hidden_field :device_id, :value => params[:device_id] %>

  <div class="control-group">
    <label class="control-label">名前</label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">送信データ</label>
    <div class="controls">
      <%= f.text_field :data %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "更新", :class => "btn btn-primary" %>
    <%= link_to "キャンセル", management_device_path(:id => params[:device_id]), :class => "btn" %>
  </div>
<% end %>

app/views/remote/index.html.erb
<legend>リモートコントロール</legend>

<div class="remote">
  <% @devices.each do |i| %>
    <% if i.ir_signal.count != 0 %>
    <h4><%= link_to i.name, "#" %></h4>
    <table>
      <tr>
      <% i.ir_signal.each do |s| %>
        <td><%= button_to s.name, ir_send_remote_path(:id => s.id), :class => "btn send" %></td>
      <% end %>
      </tr>
    </table>
    <% end %>
  <% end %>
</div>